### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by ivantsepp** [codeclimate/codeclimate-csslint#1]
For some reason, the csslint is reporting things in `vendor` (for example, I have scss gem) even though vendor is part of the exclude_paths in the codeclimate config.

I'm still looking into why that is. Let me know if you would like me to set an example repo to test this!

**Comment by GordonDiggs** [comment]
@ivantsepp I would love to see an example! At the very least, can you post your .codeclimate.yml file?

**Comment by ivantsepp** [comment]
Of course! I created this testing repo: https://github.com/ivantsepp/codeclimate_test. 

What's weird is that if sass is the only gem, this works fine. My guess is that exclude_path is a very big array and somewhere information is being dropped?

**Comment by mrb** [comment]
@ivantsepp It looks like you need to indent your exclude paths here: https://github.com/ivantsepp/codeclimate_test/blob/master/.codeclimate.yml#L12 - try that and let us know if it works. Thanks!

**Comment by GordonDiggs** [comment]
@ivantsepp Going to look into this today! Will report back with my findings.

**Comment by jonathancadepowers** [comment]
@ivantsepp Hey! Thanks for the report, and sorry for the trouble.

We just released a new version of the CLI today (version 0.0.9). Go ahead and try updating and then running a new analysis.

To update: `brew update && brew upgrade codeclimate`.

**Comment by jhmilan** [comment]
Unfortunately it is still failing. I'm assuming the "ratings:" "paths" say codeclimate what to explore.

It takes a long while and looks like it exhuast memory. I did a small test only providing a single small file within this paths and same result. Long analysis + crash. Quite odd.

**Comment by ivantsepp** [comment]
Hmm, still doesn't seem to be working. I dug in a little more
```
codeclimate_test[master] $ docker run --rm --cap-drop all --label com.codeclimate.label=a9208835-dce4-4e73-b2cb-69c084fbee0f --name cc-engines-csslint-d383ab0d-f149-4179-99d3-9db5496033f6 --memory 912005000 --memory-swap -1 --net none --volume /Users/ivantse/Desktop/codeclimate_test:/code:ro --env-file ~/Desktop/temp.txt codeclimate/codeclimate-csslint printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=d251a2dca775
HOME=/root
```

It's interesting that `~/Desktop/temp.txt codeclimate/codeclimate-csslint` is 65536 characters long. But when I drop it to 65535, `printenv` works. I hope that information helps! Unfortunately, I don't know docker enough to dig in deeper.

**Comment by GordonDiggs** [comment]
@ivantsepp a ha! Good find. Using the `envfile` was a workaround for a smaller limit on the number of characters using `--env`. Looks like we have a more general problem to solve and we will take a look!

**Comment by GordonDiggs** [comment]
@ivantsepp your issue here should be resolved if you update the CLI! Let me know if that's not the case and we can re-open
